### ISSUE TITLE
S3 Smithy model requires `?x-id=<operation>` but the S3 service doesn't

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy#1030]
This was initially reported in https://github.com/awslabs/smithy-rs/issues/1012 and we're reaching out for support. It seems like the S3 service is accepting requests without e.g. `x-id=GetObject` in the query string ([their docs don't even mention this param](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax)), yet their Smithy model is marking that param as required.

```
                "smithy.api#http": {
                    "method": "GET",
                    "uri": "/{Bucket}/{Key+}?x-id=GetObject",
                    "code": 200
                }
```

cc  @guymguym

**Comment by mtdowling** [comment]
The URIs S3 uses caused conflicts in Smithy's URI conflict validator, so we added these query string parameters to de-conflict them. They're ignored by S3. Was this causing an issue?

**Comment by david-perez** [comment]
@mtdowling 

> They're ignored by S3. Was this causing an issue?

@guymguym wants to build [a service with the exact same behavior as S3](https://github.com/s3d-rs/s3d).

**Comment by guymguym** [comment]
Hi

I documented the collisions that I see in S3 in this comment - https://github.com/awslabs/smithy-rs/issues/1012#issuecomment-1023243176. 

There seem to be few cases which the model is not able to disambiguate without x-id:
1. Route based on a required http header existence (e.g x-amz-copy-source)
2. Route based on existence of a required query key which is also an input field (e.g uploadId and partNumber)
3. Remaining POST cases - some might require the x-id because of a conflict with case1/2, but there are some which I didn't understand why x-id was needed, such as WriteGetObjectResponse, RestoreObject, SelectObjectContent, DeleteObjects.

I think case 1 and case 2 should be feasible to resolve in smithy if it supports routing based on existence of a header or  query key. Headers might require another field in the http trait next to uri, but query can be added in a similar way to the current fixed-value url query such as `"uri": "/{Bucket}/{Key+}?uploadId=*"`.

Thanks, LMKWYT

**Comment by sugmanue** [comment]
We will analyze how to work around this issue, one idea would be to add an special suppression that allows to say: "don't validate the URIs for conflicts, the service knows how to handle those", then we can change the S3 model to add this suppression and remove the `x-id` query params that are there to disambiguate the URIs.

**Comment by guymguym** [comment]
Thanks @sugmanue. CC @Nugine for https://github.com/Nugine/s3s.

**Comment by sugmanue** [comment]
The way S3 routes request is not fully compatible with http bindings, they use on top of URI headers which we don't support. These query params are there as a way to workaround this issue. If we were to support this without the synthetic query params we will need to define a new protocol which is probably too much overhead for little value. We were able to remove some of these after specificity routing but will continue to use the remaining synthetic for the time being.
