### ISSUE TITLE
HttpUriConflict while defining multiple operations inside a service

### ISSUE THREAD

**Issue by protyay** [smithy-lang/smithy#1512]
I'm defining multiple operations inside a resource and adding that resource to the service shape. 
During Smithy build, I get `HttpUriConflict` 
```
Operation URI, `/dc/labor/shift-planning/v1/input/{screenId}/tabs`, conflicts with other operation URIs in the same service: [`com.amazon.dclaborshiftplanningservice#FetchFilters` (/dc/labor/shift-planning/v1/input/{screenId}/{tabKey}/filters)]
```
Smithy Code
```
resources: [
        PickStrategyResource,
        ReportsPageResource,
        InputPageResource
    ]

resource InputPageResource {
    operations: [
        FetchTabs
        FetchInputPageContent
        SaveUserOverrides
    ]
}

@http(
    method: "GET",
    uri: "/dc/labor/shift-planning/v1/input/{screenId}/tabs"
)
operation FetchTabs {
// structures
}
@http(
    method: "GET",
    uri: "/dc/labor/shift-planning/v1/input/{screenId}/{tabKey}/filters"
)
operation FetchFilters {
}
```
Does that mean all resource operations in a given service closure should have the same URI ? 😕 

As a workaround, I'm not binding all my `resources` to the `service` shape and the build runs fine, but the downside is probably I have to repeat the `errors` property in each of the operation shapes. 
Do I understand these correctly ?

**Comment by sugmanue** [comment]
> Does that mean all resource operations in a given service closure should have the same URI ? 😕

No, it does mean that the two patterns 

* `/dc/labor/shift-planning/v1/input/{screenId}/tabs`
* `/dc/labor/shift-planning/v1/input/{screenId}/{tabKey}/filters`

conflict according to the rules in the specification, see [here](https://smithy.io/2.0/spec/http-bindings.html?highlight=http%20bindings#pattern-validation-and-conflict-avoidance). In particular this bit

> A label and a literal SHOULD NOT both occupy the same segment in patterns which are equivalent to that point if they share a host.

You can workaround this by slightly changing one of the URI's, for instance by using `tabs` and `filters` as prefix rather than a suffix, not ideal but should unblock you.

We are aware that sometimes, such as in this case, the URI's don't actually conflict with each other. We are planning to publish soon a design that changes the rules to allow URI's such as these along side those that _might conflict_ and specify how to solve any conflicts at runtime by using the most specific one, similar to what [API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-routes.html) does. 

I will update this issue when the RFC is published to get feedback and make sure that it does solve your use case.

**Comment by protyay** [comment]
Yeah, thanks. I was actually aiming for a hierarchical modelling pattern in the URIs and encountered this issue.

**Comment by sugmanue** [comment]
I have submitted a [draft pull request](https://github.com/awslabs/smithy/pull/1539) for our current thinking about how to relax this restriction, if you have time we will appreciate your feedback on this proposal

**Comment by sugmanue** [comment]
Apologies for not updating this issue before, we have released specificity routing which allows those URI to coexist. See the [documentation here](https://smithy.io/2.0/spec/http-bindings.html#specificity-routing).
