### ISSUE TITLE
Support for hexadecimal literals

### ISSUE THREAD

**Issue by mcmasn-amzn** [smithy-lang/smithy#1620]
Use case: I would like to define an `intEnum` with values expressed using hex notation. I don't care how this is serialized over the wire -- I'm just interested in the representation in docs and code.

### Example
I want to model [RFC 1997](https://www.rfc-editor.org/rfc/rfc1997.html). This defines some well-known constants which are typically written in hex.
```
intEnum BgpWellKnownCommunity {
    NO_EXPORT = 0xFFFFFF01
    NO_ADVERTISE = 0xFFFFFF02
    NO_EXPORT_SUBCONFED = 0xFFFFFF03
}
```

Because hex literals aren't supported, I have to convert to an integer (4294967041 instead of 0xFFFFFF01), which is less readable.

**Comment by jvschneid** [comment]
Hi there @mcmasn-amzn, thanks for bringing this idea to us! 

Since this change can impact model loading capabilities in a incompatible way and demand for this change is low we've moved this request into our list of possible features in case of a new IDL version release and will be closing this issue for now.
