### ISSUE TITLE
Nullability Index uses `@input` trait but should consider operations instead

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy#2012]
Currently, the nullability index uses the `@input` trait to determine if a shape is an input. However, this is unreliable and causes unexpected failures if this trait has been missed.

Consider updating the `CLIENT_CAREFUL` mode to consider whether a shape actually is an input instead of the input trait (or supplying a smithy normalizer to add the input trait)

**Comment by mtdowling** [comment]
This was by design since `@input` requires that the shape isn't reused in other places throughout the model. It codifies the intent that a shape is just going to ever be input. If a generator has a requirement that all shapes used as input have the `@input` trait, the generator can do a model transform to either apply the trait when possible or synthesize an input shape otherwise. Directed codegen abstractions from the reference implementation can do this: https://github.com/smithy-lang/smithy/blob/main/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java#L225
