### ISSUE TITLE
Loading via Smithy and Json produces different result

### ISSUE THREAD

**Issue by daddykotex** [smithy-lang/smithy#2150]
I have repro, [runnable via scastie](https://scastie.scala-lang.org/v0O4ihoLSXSOZHwuCjpPwg).

Given the following Smithy:

```smithy
$version: "2.0"

namespace a_test

@mixin
structure A {
    @required
    aMember: String
}

@mixin
structure B {
    @required
    aMember: String
}

structure MyStruct with [A, B] {
}
```

When you load this model through a `ModelAssembler` and extract the mixins of `a_test#MyStruct$aMember`, you'll get:
`[a_test#A$aMember, a_test#B$aMember]`, but if you serialize to json and then load it again, you'll get: `[a_test#B$aMember]`.

I'd like to fix it, but I'm not sure which one is at fault. I'd think the json one is at fault, and I believe the faulty logic is in `software.amazon.smithy.model.loader.ApplyMixin`.

Let me know which one is wrong, and I can work on a fix

**Comment by JordonPhillips** [comment]
I found the problem. So that rogue apply statement is the thing that revealed the bug, though it isn't itself the real issue. This issue will surface for any mixin where multiple mixins affect the same member and a trait is apparently introduced by the final shape.

The problem is [right here](https://github.com/smithy-lang/smithy/blob/main/smithy-model/src/main/java/software/amazon/smithy/model/loader/ApplyMixin.java#L108). This block will effectively overwrite the existing builder. There's [a block above that](https://github.com/smithy-lang/smithy/blob/main/smithy-model/src/main/java/software/amazon/smithy/model/loader/ApplyMixin.java#L88) which specifically wants to account for multiple mixins, but the result is being ignored in this case.

**Comment by JordonPhillips** [comment]
The saga continues. It seems there was some broad assumption that members wouldn't be touched by multiple mixins.

**Comment by daddykotex** [comment]
Thanks a bunch @JordonPhillips, I certainly did not realize the serialized model was invalid.

**Comment by JordonPhillips** [comment]
It's not invalid, semantically it is equivalent, it's just a bit strange. There's probably a good reason for doing that which I'm forgetting at the moment
