### ISSUE TITLE
@restJson1 and `charset=utf8` in the header

### ISSUE THREAD

**Issue by x1a0** [smithy-lang/smithy#2173]
Hi,

Probably a stupid question - I have a service defined with `@restJson1`. The incoming requests that have header `Content-Type: application/json` work fine.
However if they carry header `Content-Type: application/json; charset=utf8`, the server just returns:
```
415 Unsupported Media Type
```

Is there anyway to configure the header value matching somehow?
Thanks in advance.

**Comment by kstich** [comment]
This is a property of the server operating on the protocol.

If this is on API Gateway, it may be related to the [`@aws.apigateway#integration` trait's](https://smithy.io/2.0/aws/amazon-apigateway.html#aws-apigateway-integration-trait) `passThroughBehavior` member. Otherwise, I'd recommend reaching out to the team that maintains the service implementation for `@restJson1`.
