### ISSUE TITLE
`TraitDiffRule$Severity` type change in 1.46.0

### ISSUE THREAD

**Issue by kubukoz** [smithy-lang/smithy#2243]
Hi!

I was trying to [update our version of Smithy from 1.45.0 to 1.47.0 in smithy4s](https://github.com/disneystreaming/smithy4s/pull/1485), but bumped into an issue: our generated code for `smithy.api` breaks binary compatibility against its previous version.

One of such breakages, probably the most obvious one is this:

```
method severity()smithy.api.TraitChangeSeverity in class smithy.api.TraitDiffRule has a different result type in current version, where it is smithy.api.Severity rather than smithy.api.TraitChangeSeverity
```

I recognize this may an "us" problem more than Smithy's problem, but is this kind of breakage expected in 1.x? Even smithy-diff considers an enum shape rename an ERROR:

```scala
//> using dep software.amazon.smithy:smithy-model:1.47.0
//> using dep software.amazon.smithy:smithy-diff:1.47.0
import software.amazon.smithy.model.Model
import software.amazon.smithy.diff.ModelDiff
import scala.jdk.CollectionConverters._

def parse(s: String) = Model
  .assembler()
  .addUnparsedModel("test.smithy", s)
  .assemble()
  .unwrap()

@main def run = {
  val m1 = parse("""$version: "2"
  |namespace demo
  |
  |@private
  |structure Hello {
  |  greeting: Greeting
  |}
  |
  |@private
  |enum Greeting {
  |  FOO
  |  BAR
  |}
  |""".stripMargin)
  val m2 = parse("""$version: "2"
  |namespace demo
  |
  |@private
  |structure Hello {
  |  greeting: GreetingNew
  |}
  |
  |@private
  |enum GreetingNew {
  |  FOO
  |  BAR
  |}
  |""".stripMargin)

  ModelDiff.builder().oldModel(m1).newModel(m2).compare().getDiffEvents().asScala.foreach(println)
// [NOTE] demo#GreetingNew: Added enum `demo#GreetingNew` | AddedShape test.smithy:9:1
// [ERROR] demo#Hello$greeting: The shape targeted by the member `demo#Hello$greeting` changed from `demo#Greeting` (enum) to `demo#GreetingNew` (enum). The `smithy.api#enum` trait was found on the target, so the name of the targeted shape matters for codegen. | ChangedMemberTarget test.smithy:5:3
}
```

**Comment by mtdowling** [comment]
Sorry to hear that impacted you. This was a private shape in the prelude, so it seemed like fair game and not a breaking change to change it given we needed to reuse this shape in other parts of the prelude for less specific purposes. I'm surprised something would codegen private shapes from smithy.api like this. If that's a requirement of smithy4s, we'll be more careful of changes to the prelude in the future.

**Comment by Baccata** [comment]
You can close the ticket, let's talk about it in another channel, clearly the fact that it's private makes it fair game

**Comment by Baccata** [comment]
@mtdowling, apologies but I'm compelled to ask @kubukoz re-open the issue, after giving it some further thoughts. I'm happy to open a new issue if you think it'd be preferable.  

The concept carried by `@private` in [smithy](https://smithy.io/2.0/spec/constraint-traits.html#private-trait) prevents the direct referencing of a shape from other namespaces. However, it doesn't prevent their indirect referencing. It is the case, for instance, for the `smithy.api#Example` shape that is used in the [smithy.api#examples](https://github.com/smithy-lang/smithy/blob/7c6228f351d85dab343af614181bbaa41893737e/smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy#L392-L394) trait. 

If we make the parallel with Java, it'd be akin to having a public class carry an accessor, the return type of which would be private. This would simply not pass compilation. 

Now the thing is that code-generating traits can be useful. As a matter of fact, the original smithy tooling is [facilitating this usecase](https://github.com/smithy-lang/smithy/tree/7c6228f351d85dab343af614181bbaa41893737e/smithy-trait-codegen). Smithy4s generates code for all shapes from all models it encounters, trait or not, and for better or worse, this generated code is used in applications (as opposed to tooling). 

If we avoided the generation of private trait shapes from the prelude, we'd find ourselves in a conundrum with regards to "what should we do with members of public shapes that target private shapes ?". Omitting them is hardly a solution : in the case of `@examples`, the `smithy.api#Example` is the valuable bit of information, despite being tagged as private in the smithy prelude. 

So my point is that, the smithy `@private` doesn't make the renaming of shapes fair-game after all, because if end users can "instantiate" traits and provide values for the private shapes, then users should be in the right to want to query/manipulate those values using generated code, which implies that `@private` shapes should be subject to a similar degree of strict-ness/principle-ness than other shapes when it comes to evolving them. 

> If that's a requirement of smithy4s, we'll be more careful of changes to the prelude in the future. 

Therefore, it'd be greatly appreciated if you folks could indeed be more careful of changes to the prelude in the future.

**Comment by mtdowling** [comment]
That makes sense. We use protocol and validation traits at runtime too in some code bases. Those code bases don’t generate documentation traits and model specific traits like what’s mentioned in the issue, so it wasn’t an issue there. If something is generating them all, then I could see how it’d be impacted.

I don’t think it’s worth rolling back now that it’s deployed. To prevent an unintended break of smithy4s, we could potentially add a chain build or something via GitHub actions from this repo to smithy4s (contributions here are very welcome).

**Comment by Baccata** [comment]
Yeah no need to rollback this time around, we'll manage. I'm more interested to avoid a future mis-hap

@kubukoz and I will discuss contributing a "chain build", see what'd be possible.

Thank you for your understanding 👍
