### ISSUE TITLE
Parsing for `ParameterTypes` has unintuitive casing rules

### ISSUE THREAD

**Issue by landonxjames** [smithy-lang/smithy#2347]
The `string` and `boolean` types are `equalsIgnoreCase`, but the `stringArray` type is just compared with `equals`. This leads to unintuitive behavior like `String` and `Boolean` being valid types, but `StringArray` failing.

https://github.com/smithy-lang/smithy/blob/2cd3579c7fad1322798ebb62dd9f47b13ca4beb3/smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/parameters/ParameterType.java#L46-L60

**Comment by sugmanue** [comment]
Hi Landon, 

Thank you for reporting this issue, I've created an PR to also use `equalsIgnoreCase` for the `stringArray` type.

**Comment by sugmanue** [comment]
I discussed this with the team, this inconsistency is there by design (see [thread here](https://github.com/smithy-lang/smithy/pull/2266#discussion_r1586579002)). We wanted all the type names to be not case sensitive but the first two when in and we cannot change those to avoid breaking compatibility. Going forward all new type names will be not case sensitive.

**Comment by sugmanue** [comment]
Let us know if you have any further questions or concerns.
