### ISSUE TITLE
Counterintuitive`ModelAssembler`'s default caching behavior 

### ISSUE THREAD

**Issue by ghostbuster91** [smithy-lang/smithy#2441]
Hello,

We recently discovered that `ModelAssembler` implements caching when loading external jars, but this cache only considers the file path of the jars. It does not account for file attributes or the content of the jar itself.

This behavior can be counterintuitive and potentially leads to significant debugging challenges, as modifications to jar files may not be recognized under certain conditions.

To provide some context: we encountered this issue while working with SBT, the Scala build tool, which by default runs tests in the same Java process. Because the caching is path-based, changes to jar files during local development were not reflected in tests, causing unexpected behaviors.

Thank you for looking into this.

**Comment by kstich** [comment]
Are you creating the `ModelAssembler` as part of your tooling? If so, It reacts to a `assembler.disableJarCache` property (set via `putProperty` to `true`) to disable JAR caching.

**Comment by ghostbuster91** [comment]
Yes, we are aware of that option. I am just saying that it shouldn't be the default behavior.

**Comment by mtdowling** [comment]
This kind of JAR caching is the default behavior in Java. I wonder if there's an issue open with the JDK about this? If the implementation in Java changed to account for files sizes/last modified/etc, then so would the cache used here with URLConnection.

I don't think it's a good idea for us to change the default behavior here now since people could be relying on the cache and would notice large latency increases. As kstich points out, this is something that can be controlled per ModelAssembler instance using `assembler.disableJarCache`.

**Comment by ghostbuster91** [comment]
> I don't think it's a good idea for us to change the default behavior here now

I agree, maybe something to consider for 2.x then?

**Comment by kstich** [comment]
Potentially, though we're not currently considering a 2.x. I'm going to close this issue for now as the assembler property handles the core problem.

**Comment by kubukoz** [comment]
To be honest, it doesn't really handle the problem - it's either "all or nothing". You can get the cache, which fails to detect a miss when the file changes, or no cache at all, making _everything_ slower, not just the duplicate calls to a file that potentially has changed. The desired outcome would've been to have a cache that you can trust :)
