### ISSUE TITLE
Promote certain failures to fail the build (was "Fail build when using Unreferenced shapes")

### ISSUE THREAD

**Issue by filletofish** [smithy-lang/smithy#856]
HI all, 

Is it possible to fail the build when discovering Unreferenced shape in the model? 

For example, instead of receiving this note in the build logs, I would have it as `Error` and fail the whole build.

```
     [java] NOTE: com.example.service#InvalidInputException (UnreferencedShape)
     [java]      @ /path/to/smithy-model/errors.smithy
     [java]      |
     [java]   15 | structure InvalidInputException {
     [java]      | ^
     [java]      = The structure shape is not connected to from any service shape.
```

I personally sometimes miss those notes from the build logs. Then I waste time on finding the root cause for the errors in the service, only to find out that I forgot to reference the shape properly. If I had an option to enable this flag and fail my builds, it would save me some time during implementation.

**Comment by mtdowling** [comment]
I could see this as fitting nicely as a smithy-build.json configuration setting. Putting it in model metadata alongside `validators` and `suppressions` seems like the wrong approach because other teams building your model might not care about UnreferencedShapes. For example:

```
{
    "version": "1.0",
    "validation": {
        "elevate": [
            {"id": "UnreferencedShape", "severity": "DANGER"}
        ]
    }
}
```

Not sure if "elevate" is the right word. The use of an object rather than just a list of strings allows us to add more features too (like if we want to limit the elevation to specific namespaces or to specific selectors).
